config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :exercises
  resources :workouts
  
  get 'pages/about'
  get 'pages/calendar'
  get 'pages/random'
  root 'pages#home'

  post 'generate_random_workout', to: 'workouts#generate_random_workout', as: :generate_random_workout
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/workout.rb
class Workout < ApplicationRecord
    validates :name, presence: true
    validates :date, presence: true
    has_many :exercises
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: %i[ show edit update destroy ]

  # GET /workouts or /workouts.json
  def index
    @workouts = Workout.all
  end

  # GET /workouts/1 or /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts or /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to workout_url(@workout), notice: "Workout was successfully created." }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1 or /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to workout_url(@workout), notice: "Workout was successfully updated." }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1 or /workouts/1.json
  def destroy
    @workout.destroy

    respond_to do |format|
      format.html { redirect_to workouts_url, notice: "Workout was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workout_params
      params.require(:workout).permit(
        :name, 
        :date, 
        :exercise1, :exercise1_weight, :exercise1_reps, :exercise1_sets,
        :exercise2, :exercise2_weight, :exercise2_reps, :exercise2_sets,
        :exercise3, :exercise3_weight, :exercise3_reps, :exercise3_sets,
        :exercise4, :exercise4_weight, :exercise4_reps, :exercise4_sets,
        :exercise5, :exercise5_weight, :exercise5_reps, :exercise5_sets,
        :exercise6, :exercise6_weight, :exercise6_reps, :exercise6_sets,
        :cardio, :round_time, :cardio_sets,
      )
    end

    
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
  def compare_attributes(attribute_name, value1, value2)
    if value2.to_f > value1.to_f
      content_tag(:p, "Improved #{attribute_name}: #{value2} (Previously: #{value1})")
    elsif value2.to_f < value1.to_f
      content_tag(:p, "Decreased #{attribute_name}: #{value2} (Previously: #{value1})")
    else
      content_tag(:p, "#{attribute_name} stayed the same: #{value2}")
    end
  end
end

module ApplicationHelper
  def random_workout(workout_number)
    exercise_data = [
      { name: "Push-ups", reps: rand(5..20), sets: rand(2..4) },
      { name: "Sit-ups", reps: rand(10..30), sets: rand(2..4) },
      { name: "Squats", reps: rand(8..15), sets: rand(2..4) },
      { name: "Planks", reps: "#{rand(10..30)} seconds", sets: rand(2..4) },
      { name: "Jumping Jacks", reps: rand(20..50), sets: rand(2..4) },
      { name: "Lunges", reps: rand(8..15), sets: rand(2..4) },
      { name: "Burpees", reps: rand(5..15), sets: rand(2..4) },
      { name: "Mountain Climbers", reps: rand(20..40), sets: rand(2..4) }
    ]

    workout_name = "Workout #{workout_number}"
    workout = "<h2>#{workout_name}</h2>"

    exercise_data.each do |exercise|
      workout << "<p>#{exercise[:name]} - #{exercise[:reps]} reps (#{exercise[:sets]} sets)</p>"
    end

    workout.html_safe
  end
end

app/views/workouts/_form.html.erb
<%= form_with(model: workout) do |form| %>
  <% if workout.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(workout.errors.count, "error") %> prohibited this workout from being saved:</h2>
      <ul>
        <% workout.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <article>
    <div>
      <strong><%= form.label :date, class: "form-label" %></strong>
      <%= form.date_field :date, class: "form-control" %>
    </div>

    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <% (1..6).each do |exercise_number| %>
      <div>
        <%= form.label "exercise#{exercise_number}", style: "display: block" %>
        <%= form.select "exercise#{exercise_number}", Exercise::ALL_EXERCISES %>
      </div>

      <div>
        <%= form.label :weight, style: "display: block" %>
        <%= form.select "exercise#{exercise_number}_weight", options_for_weight_dropdown %>
      </div>

      <div>
        <%= form.label :sets, style: "display: block" %>
        <%= form.select "exercise#{exercise_number}_sets", options_for_sets_dropdown %>
      </div>

      <div>
        <%= form.label :repetitions, style: "display: block" %>
        <%= form.select "exercise#{exercise_number}_reps", options_for_repetitions_dropdown %>
      </div>
    <% end %>
</article>

<article>
    <div>
      <%= form.label :cardio, style: "display: block" %>
      <%= form.select :cardio, Exercise::Cardio %>
    </div>

<%# sets %>
    <div> 
      <%= form.label :cardio_sets, style: "display: block" %>
      <%= form.select :cardio_sets, options_for_sets_dropdown %>
    </div>

<%# duration %>
    <div>
      <%= form.label :round_time, style: "display: block" %>
      <%= form.select :round_time, options_for_cardio_duration %>
    </div>

</article>

    <div>
      <%= form.submit %>
    </div>
<% end %>

app/views/workouts/_workout.html.erb
<div id="<%= dom_id workout %>">
  <article id="article">
  
    <table role="grid">
      <hgroup>
        <h3><strong><%= workout.name %></strong></h3>
        <h2><strong><%= workout.date %></strong></h2>
    </hgroup>
      <thead>
        <tr>
          <th scope="col"><strong>Exercise</strong></th>
          <th scope="col"><strong>Weight</strong></th>
          <th scope="col"><strong>Sets</strong></th>
          <th scope="col"><strong>Repetitions</strong></th>
        </tr>
      </thead>
      <tbody>
        <% (1..6).each do |exercise_number| %>
          <% exercise_field = "exercise#{exercise_number}" %>
          <% weight_field = "#{exercise_field}_weight" %>
          <% sets_field = "#{exercise_field}_sets" %>
          <% reps_field = "#{exercise_field}_reps" %>
          <% if workout.send(exercise_field) != "-" %>
            <tr>
              <td><%= workout.send(exercise_field) %></td>
              <td><%= workout.send(weight_field) %></td>
              <td><%= workout.send(sets_field) %></td>
              <td><%= workout.send(reps_field) %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <footer>
    <table role="grid">
      <thead>
        <tr>
          <th scope="col"><strong>Cardio</strong></th>
          <th scope="col"><strong>Sets/Laps</strong></th>
          <th scope="col"><strong>Duration</strong></th>
        </tr>
      </thead>
      <tbody>
        <% if workout.cardio != "-" %>
        <tr>
          <td><%= workout.cardio %></td>
          <td><%= workout.cardio_sets %></td>
          <td><%= "#{workout.round_time.to_s} minutes" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </footer>
  </article>
</div>

app/views/workouts/edit.html.erb
<h1>Editing workout</h1>

<%= render "form", workout: @workout %>

<br>

<div>
  <%= link_to "Show this workout", @workout %> |
  <%= link_to "Back to workouts", workouts_path %>
</div>

app/views/workouts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Workouts</h1>

<div id="workouts">
  <% @workouts.each do |workout| %>
    <%= render workout %>
    <p>
      <%= link_to "Show this workout", workout %>
    </p>
  <% end %>
</div>

<%= link_to "New workout", new_workout_path %>

app/views/workouts/new.html.erb
<h1>New workout</h1>

<%= render "form", workout: @workout %>

<br>

<div>
  <%= link_to "Back to workouts", workouts_path %>
</div>

app/views/workouts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @workout %>

<div>
  <%= link_to "Edit this workout", edit_workout_path(@workout) %> |
  <%= link_to "Back to workouts", workouts_path %>

  <%= button_to "Destroy this workout", @workout, method: :delete %>
</div>