config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :exercises
  resources :workouts
  
  get 'pages/about'
  get 'pages/calendar'
  get 'pages/random'
  root 'pages#home'

  post 'generate_random_workout', to: 'workouts#generate_random_workout', as: :generate_random_workout
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/calendar.html.erb
<p style="color: green"><%= notice %></p>
<h1>My Progress</h1>

<h5>Current Weight:</h5>
<% last_two_workouts = @workouts.last(2) %>

<% if last_two_workouts.size == 2 %>
  <h3>Last Two Workouts Comparison:</h3>
<article>
  <table role="grid">
    <thead>
      <tr>
        <th><strong>Exercise</strong></th>
        <th><strong>Weight</strong></th>
        <th><strong>Sets</strong></th>
        <th><strong>Repetitions</strong></th>
      </tr>
    </thead>
    <tbody>
      <% (1..6).each do |exercise_number| %>
        <% exercise_name = Exercise::ALL_EXERCISES[exercise_number] %>
        <% exercise_data_1 = last_two_workouts[0]["exercise#{exercise_number}_weight"] %>
        <% exercise_data_2 = last_two_workouts[1]["exercise#{exercise_number}_weight"] %>
        <% exercise_sets_1 = last_two_workouts[0]["exercise#{exercise_number}_sets"] %>
        <% exercise_sets_2 = last_two_workouts[1]["exercise#{exercise_number}_sets"] %>
        <% exercise_reps_1 = last_two_workouts[0]["exercise#{exercise_number}_reps"] %>
        <% exercise_reps_2 = last_two_workouts[1]["exercise#{exercise_number}_reps"] %>

        <% if exercise_data_1.present? && exercise_data_2.present? &&
             exercise_sets_1.to_i > 0 && exercise_sets_2.to_i > 0 &&
             exercise_reps_1.to_i > 0 && exercise_reps_2.to_i > 0 %>
          
          <tr>
            <td><%= exercise_name %></td>
            <td><%= compare_attributes("Weight", exercise_data_1, exercise_data_2) %></td>
            <td><%= compare_attributes("Sets", exercise_sets_1, exercise_sets_2) %></td>
            <td><%= compare_attributes("Repetitions", exercise_reps_1, exercise_reps_2) %></td>
          </tr>
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</article>
<% else %>
  <p>There are not enough workouts to compare.</p>
<% end %>

app/views/pages/home.html.erb
<h1>Welcome to the Fitness App!</h1>
<p>Use it as a log of all the exercises used during your workouts. More to come!</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/random.html.erb
<h1>Random Workouts</h1>

 <!-- Pass a workout number, e.g., 1 -->
 <article>
<div class="grid">
  <div><%= random_workout(1) %></div>
  <div><%= random_workout(2) %></div>
  <div><%= random_workout(3) %></div>
</div>

<%= button_to 'Generate Random Workout', pages_random_path, class: 'btn btn-primary' %>


</article>