config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :exercises
  resources :workouts
  
  get 'pages/about'
  get 'pages/calendar'
  get 'pages/random'
  root 'pages#home'

  post 'generate_random_workout', to: 'workouts#generate_random_workout', as: :generate_random_workout
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: %i[ show edit update destroy ]

  # GET /exercises or /exercises.json
  def index
    @exercises = Exercise.all
  end

  # GET /exercises/1 or /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises or /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to exercise_url(@exercise), notice: "Exercise was successfully created." }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1 or /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to exercise_url(@exercise), notice: "Exercise was successfully updated." }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1 or /exercises/1.json
  def destroy
    @exercise.destroy

    respond_to do |format|
      format.html { redirect_to exercises_url, notice: "Exercise was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exercise_params
      params.require(:exercise).permit(:name, :category)
    end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_exercise.html.erb
<div id="<%= dom_id exercise %>">
<article>

  <div class="grid">
  <div>
    <%= exercise.name %>
    <%= exercise.category%>
  </div>
</article>

</article>

app/views/exercises/_form.html.erb
<%= form_with(model: exercise) do |form| %>
  <% if exercise.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
        <% exercise.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing exercise</h1>

<%= render "form", exercise: @exercise %>

<br>

<div>
  <%= link_to "Show this exercise", @exercise %> |
  <%= link_to "Back to exercises", exercises_path %>
</div>

app/views/exercises/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Exercises</h1>

<div id="exercises">
  <% @exercises.each do |exercise| %>
    <%= render exercise %>
    <p>
      <%= link_to "Show this exercise", exercise %>
    </p>
  <% end %>
</div>

<%= link_to "New exercise", new_exercise_path %>

app/views/exercises/new.html.erb
<h1>New exercise</h1>

<%= render "form", exercise: @exercise %>

<br>

<div>
  <%= link_to "Back to exercises", exercises_path %>
</div>

app/views/exercises/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @exercise %>

<div>
  <%= link_to "Edit this exercise", edit_exercise_path(@exercise) %> |
  <%= link_to "Back to exercises", exercises_path %>

  <%= button_to "Destroy this exercise", @exercise, method: :delete %>
</div>